# Generated by Django 3.1.1 on 2020-09-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_carrito_detalle_orden_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='sub_total',
        ),
    ]
